repos:
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
      language_version: python3.8
      args: [--line-length=70]
-   repo: https://github.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8
      args: ['--ignore=E402, E302']
-   repo: https://github.com/econchick/interrogate
    rev: 1.4.0  
    hooks:
    - id: interrogate
      args: [-vv, -i, --fail-under=80]
-   repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
    - id: isort
      args: [ "--profile", "black" ]